package com.myspace.materialrestocking;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BreweryRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BREWERYREQUEST_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BREWERYREQUEST_ID_GENERATOR", sequenceName = "BREWERYREQUEST_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Beer Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label(value = "Number of Batches")
	private java.lang.Integer count;

	public BreweryRequest() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Integer getCount() {
		return this.count;
	}

	public void setCount(java.lang.Integer count) {
		this.count = count;
	}

	public BreweryRequest(java.lang.Long id, java.lang.String type,
			java.lang.Integer count) {
		this.id = id;
		this.type = type;
		this.count = count;
	}

}