package com.myspace.materialrestocking;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Material implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "MATERIAL_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "MATERIAL_ID_GENERATOR", sequenceName = "MATERIAL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Unit")
	private java.lang.String unit;

	@org.kie.api.definition.type.Label("Value")
	private java.math.BigDecimal value;

	@org.kie.api.definition.type.Label(value = "Enough")
	private java.lang.Boolean enough;

	public Material() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public java.math.BigDecimal getValue() {
		return this.value;
	}

	public void setValue(java.math.BigDecimal value) {
		this.value = value;
	}
	
	public void convertFromLb() {
		this.value = this.value.multiply(new java.math.BigDecimal(0.45359));
	}
	
	public void convertFromOz() {
		this.value = this.value.multiply(new java.math.BigDecimal(0.02834));
	}

	public java.lang.Boolean getEnough() {
		return this.enough;
	}
	
	

	public void setEnough(java.lang.Boolean enough) {
		this.enough = enough;
	}

	public Material(java.lang.Long id, java.lang.String type,
			java.lang.String unit, java.math.BigDecimal value,
			java.lang.Boolean enough) {
		this.id = id;
		this.type = type;
		this.unit = unit;
		this.value = value;
		this.enough = enough;
	}

}